#specify
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4.4.4"

install: 
 - npm install

script: npm test

notifications: 
 email:
  recipients: weilu544@gmail.com
  on_success: change
  on_failure: always